/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Drop {
  'id' : string,
  'name' : string,
  'listingIds' : Array<string>,
  'scheduledAt' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Listing {
  'id' : string,
  'status' : Status,
  'imageUrls' : Array<ExternalBlob>,
  'name' : string,
  'description' : string,
  'price' : string,
}
export type Status = { 'available' : null } |
  { 'selling' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addListing' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      Array<ExternalBlob>,
      Status,
    ],
    undefined
  >,
  'createDrop' : ActorMethod<
    [string, string, string, string, bigint, Array<string>],
    undefined
  >,
  'deleteDrop' : ActorMethod<[string, string, string], undefined>,
  'deleteListing' : ActorMethod<[string, string, string], undefined>,
  'editDrop' : ActorMethod<
    [string, string, string, string, bigint, Array<string>],
    undefined
  >,
  'editListing' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      Array<ExternalBlob>,
      Status,
    ],
    undefined
  >,
  'getAllDrops' : ActorMethod<[string, string], Array<Drop>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getDrop' : ActorMethod<[string, string, string], [] | [Drop]>,
  'getListing' : ActorMethod<[string], [] | [Listing]>,
  'setListingStatus' : ActorMethod<[string, string, string, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];