/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Status = IDL.Variant({
  'available' : IDL.Null,
  'selling' : IDL.Null,
});
export const BackupListingEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Text,
});
export const BackupDropEntry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'listingIds' : IDL.Vec(IDL.Text),
  'scheduledAt' : IDL.Int,
});
export const BackupData = IDL.Record({
  'listings' : IDL.Vec(BackupListingEntry),
  'drops' : IDL.Vec(BackupDropEntry),
});
export const Drop = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'listingIds' : IDL.Vec(IDL.Text),
  'scheduledAt' : IDL.Int,
});
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'imageUrls' : IDL.Vec(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        Status,
      ],
      [],
      [],
    ),
  'createDrop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'deleteDrop' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteListing' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'editDrop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'editListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        Status,
      ],
      [],
      [],
    ),
  'exportData' : IDL.Func([IDL.Text, IDL.Text], [BackupData], []),
  'getAllDrops' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Drop)], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getDrop' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Opt(Drop)], []),
  'getListing' : IDL.Func([IDL.Text], [IDL.Opt(Listing)], ['query']),
  'importData' : IDL.Func([IDL.Text, IDL.Text, BackupData], [], []),
  'setListingStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Status = IDL.Variant({ 'available' : IDL.Null, 'selling' : IDL.Null });
  const BackupListingEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Text,
  });
  const BackupDropEntry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'listingIds' : IDL.Vec(IDL.Text),
    'scheduledAt' : IDL.Int,
  });
  const BackupData = IDL.Record({
    'listings' : IDL.Vec(BackupListingEntry),
    'drops' : IDL.Vec(BackupDropEntry),
  });
  const Drop = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'listingIds' : IDL.Vec(IDL.Text),
    'scheduledAt' : IDL.Int,
  });
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'imageUrls' : IDL.Vec(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          Status,
        ],
        [],
        [],
      ),
    'createDrop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'deleteDrop' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteListing' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'editDrop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'editListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          Status,
        ],
        [],
        [],
      ),
    'exportData' : IDL.Func([IDL.Text, IDL.Text], [BackupData], []),
    'getAllDrops' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Drop)], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getDrop' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Opt(Drop)], []),
    'getListing' : IDL.Func([IDL.Text], [IDL.Opt(Listing)], ['query']),
    'importData' : IDL.Func([IDL.Text, IDL.Text, BackupData], [], []),
    'setListingStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Status],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };